### ISSUE TITLE
Search and Sql unittest issues

### ISSUE THREAD

**Issue by CeltonMcGrath** [Southpaw-TACTIC/TACTIC#1455]
**Describe the bug**
On 4.8, search_test.py and sql_test.py are failing. 

**To Reproduce**
run 
python3 src/test/search_test.py
python3 src/test/sql_test.py

For example, sql_test.py produces the following error:

E/usr/lib64/python3.7/unittest/case.py:660: ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/tactic/tactic/src/plugins/TACTIC/internal/unittest/unittest_car.spt' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback

======================================================================
ERROR: test_all (pyasm.search.sql_test.SqlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/tactic/tactic/src/pyasm/search/sql.py", line 841, in do_update
    self.cursor.execute(query)
psycopg2.ProgrammingError: missing FROM-clause entry for table "sports_car_data"
LINE 1: ...ports_car" AS SELECT "unittest"."public"."car".*, "unittest"...
                                                             ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tactic/tactic/src/pyasm/search/sql_test.py", line 38, in setUp
    self.test_env.create()
  File "/opt/tactic/tactic/src/pyasm/unittest/environment.py", line 44, in create
    installer.execute()
  File "/opt/tactic/tactic/src/tactic/command/plugin.py", line 933, in execute
    self.import_manifest(nodes)
  File "/opt/tactic/tactic/src/tactic/command/plugin.py", line 988, in import_manifest
    jobs = tools.import_data(path, commit=True)
  File "/opt/tactic/tactic/src/tactic/command/plugin.py", line 1855, in import_data
    table.commit()
  File "/opt/tactic/tactic/src/pyasm/search/sql.py", line 3946, in commit
    sql.do_update(statement)
  File "/opt/tactic/tactic/src/pyasm/search/sql.py", line 878, in do_update
    raise SqlException(str(e))
pyasm.search.sql.SqlException: missing FROM-clause entry for table "sports_car_data"
LINE 1: ...ports_car" AS SELECT "unittest"."public"."car".*, "unittest"...
                                                             ^

----------------------------------------------------------------------
Ran 1 test in 1.697s

**Expected behavior**
Executes without issue as it had on 4.7

**Comment by CeltonMcGrath** [comment]
@remkonoteboom I originally came across this issue when my own unittests started failing in a recent commit to 4.8. This is unrelated but can you also help fix this? 

Code merged in
https://github.com/Southpaw-TACTIC/TACTIC/pull/1452/
of schema.py appears to the issue. 

Logic on line 1283 was changed from,
schema_xml = SCHEMA_XML.get(code)
to,
schema_xml = SCHEMA_XML.get("code")

and this is causing an error in my unittest. My unittests use a class inherited from UnittestEnvironment. When running my tests, the following error occurs. 

Traceback (most recent call last):
  File "/opt/GitHub/arina-tactic/arinalive/tests/user_test.py", line 65, in test_all
    test_env.delete()
  File "/opt/tactic/tactic/src/pyasm/unittest/environment.py", line 53, in delete
    delete_cmd.execute()
  File "/opt/tactic/tactic/src/tactic/ui/tools/delete_wdg.py", line 1233, in execute
    sobjs = Search.eval(expr2)
  File "/opt/tactic/tactic/src/pyasm/search/search.py", line 1985, in eval
    return parser.eval(expression, sobjects=sobjects, single=single, list=list, dictionary=dictionary, vars=vars, env_sobjects=env_sobjects, show_retired=show_retired, state=state, extra_filters=extra_filters, search=search)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 228, in eval
    self.dive(new_parser)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 583, in dive
    new_parser.do_parse()
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 541, in do_parse
    value = self.parse(char)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 816, in parse
    self.result = self.dive(mode)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 583, in dive
    new_parser.do_parse()
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 541, in do_parse
    value = self.parse(char)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 1167, in parse
    self.result = self.execute_method(method_name, args)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 1251, in execute_method
    results = self.get_sobjects(search_types)
  File "/opt/tactic/tactic/src/pyasm/biz/expression.py", line 2352, in get_sobjects
    tmp_dict = Search.get_related_by_sobjects(related_sobjects, related_type, filters=filters, path=path, show_retired=self.show_retired)
  File "/opt/tactic/tactic/src/pyasm/search/search.py", line 2266, in get_related_by_sobjects
    search.add_relationship_filters(sobjects, path=path)
  File "/opt/tactic/tactic/src/pyasm/search/search.py", line 923, in add_relationship_filters
    raise SearchException("Search type [%s] is not related to search_type [%s]" % ( search_type, related_type) )
pyasm.search.search.SearchException: Search type [sthpw/login_in_group] is not related to search_type [sthpw/login_group]

**Comment by remkonoteboom** [comment]
This is obviously wrong:

schema_xml = SCHEMA_XML.get("code")

Fixed in associated pull request.
