### ISSUE TITLE
Uploading a file using client api with Python 3 causes error

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1516]
**Describe the bug**
    server.upload_file("./foo3.txt")
  File "/opt/tactic/tactic/src/client/tactic_client_lib/tactic_server_stub.py", line 1862, in upload_file
    upload.execute(path)
  File "/opt/tactic/tactic/src/client/tactic_client_lib/common/upload_multipart.py", line 105, in execute
    (status, reason, content) = self.upload(self.server_url, fields, files)
  File "/opt/tactic/tactic/src/client/tactic_client_lib/common/upload_multipart.py", line 120, in upload
    ret_value = self.posturl(url, fields, files)
  File "/opt/tactic/tactic/src/client/tactic_client_lib/common/upload_multipart.py", line 145, in posturl
    return self.post_multipart(urlparts[1], urlparts[2], fields,files, protocol)
  File "/opt/tactic/tactic/src/client/tactic_client_lib/common/upload_multipart.py", line 155, in post_multipart
    content_type, body = self.encode_multipart_formdata(fields, files)
  File "/opt/tactic/tactic/src/client/tactic_client_lib/common/upload_multipart.py", line 220, in encode_multipart_formdata
    buf.writelines(M)
TypeError: string argument expected, got 'bytes'

**To Reproduce**
Test Script: 

```
import tacticenv

from tactic_client_lib import TacticServerStub

server = TacticServerStub.get(setup=False)
server.set_server("http://192.168.115.156")

server.upload_file("./foo3.txt")
```

**Comment by remkonoteboom** [comment]
This has been fixed in the linked pull request.  The file is now converted to base64 before adding to the request.  You can also set the chunk size in the api, so that a file change be uploaded in chunks.  This is now exposed in the API.  The default chunk size is 10Mb.  There is also an offset counter which if fails, you could theoretically restart at that offset, however, this number is not available to the API function yet.

**Comment by listyque** [comment]
Will it add overhead to uploaded file size and traffic use?

**Comment by remkonoteboom** [comment]
It's not so bad.  I tried a 170Mb file and it took 400-500ms to convert to base64 and it expanded it by about 30%.  By comparison, doing an str() operation of the file takes 5 full seconds and expands it more than double. 

To be honest, I tried a few ways to send binary through, but, in the time I worked on it, I couldn't get Python3 to both accept the binary data and be able to reconvert to the exact file on the server side.   It should be possible ... maybe playing with BytesIO, however, base64 just worked, so I implemented so we at least have something working.

I figured it was better to at least have something working that it being just broken.

**Comment by listyque** [comment]
Ok. Thanks! Will be waiting for merge, then i can test it.

**Comment by remkonoteboom** [comment]
I added code to make it work with BytesIO and add straight binary to the request ... however, it turns out to be almost twice as slow as base64 conversion.  I did some timing and it appears that the slowness is in the Python requests library:

        h.request('POST', selector, body, headers)
        res = h.getresponse()

This call takes almost twice as long when using BytesIO.  Likely, this code is doing some conversion itself.  Whatever the reason, I have kept the binary code in case someone finds a reason that it is slow, but the mode is hard coded to base64.

**Comment by listyque** [comment]
Just tested it and getting this:

```
Error:  Incorrect padding
... trying again
Error:  Incorrect padding
... trying again
Error:  Incorrect padding
... trying again
Error:  Incorrect padding
... trying again
Error:  Incorrect padding
... trying again
offset:  0
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "\client\tactic_client_lib\tactic_server_stub.py", line 2022, in simple_checkin
    self.upload_file(file_path)
  File "\client\tactic_client_lib\tactic_server_stub.py", line 1867, in upload_file
    upload.execute(path)
  File "\client\tactic_client_lib\common\upload_multipart.py", line 116, in execute
    (status, reason, content) = self.upload(self.server_url, fields, files)
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by listyque** [comment]
But everything works when i disable mode = "base64"

**Comment by remkonoteboom** [comment]
What type of file is this?  The setup I have did not produce this error.

in upload_multipart.py, lines:

137         except Exception as e:
138             print("Error: ", e)

For debug, could you add this
139             raise

So we can get a stack trace on the actual error

**Comment by listyque** [comment]
It's a simple png file. Here it is:
![grid](https://user-images.githubusercontent.com/13370598/87951300-11825e00-cab1-11ea-8ed5-020b700e6e56.png)
```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "client\tactic_client_lib\tactic_server_stub.py", line 2022, in simple_checkin
    self.upload_file(file_path)
  File "client\tactic_client_lib\tactic_server_stub.py", line 1867, in upload_file
    upload.execute(path)
  File "client\tactic_client_lib\common\upload_multipart.py", line 116, in execute
    (status, reason, content) = self.upload(self.server_url, fields, files)
  File "client\tactic_client_lib\common\upload_multipart.py", line 139, in upload
    raise e
  File "client\tactic_client_lib\common\upload_multipart.py", line 133, in upload
    raise Exception(ret_value[1])
Exception: Incorrect padding
```

**Comment by remkonoteboom** [comment]
For some reason, there was some special code for a .png and it didn't work in Python3.  Removing it fixed the issue with this file.  This problem only occurred for pngs.
