### ISSUE TITLE
async_get_widget: Server Error: method "ERRORMETHOD" is not supported

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1558]
**Describe the bug**
Getting this error on the latest 4.8.
Right after opening tactic in browser and even with python api.

Also, some missing files:
DevTools failed to load SourceMap: Could not load content for http://92.63.103.46/context/spt_js/jquery/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://92.63.103.46/context/spt_js/bootstrap_material_design/bootstrap-material-design.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://92.63.103.46/context/spt_js/html2canvas.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://92.63.103.46/context/spt_js/bootstrap_material_design/bmd-bs-tactic-project.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**To Reproduce**
1. Install latest tactic 4.8
2. Start it and open in browser
3. See error message

**Comment by listyque** [comment]
Traceback (most recent call last):
  File "/opt/tactic/tactic/3rd_party/python3/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/opt/tactic/tactic/3rd_party/python3/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/opt/tactic/tactic/3rd_party/python3/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/tactic/tactic/3rd_party/python3/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/tactic/tactic/3rd_party/python3/site-packages/cherrypy/_cptools.py", line 384, in default
    raise Exception('method "%s" is not supported' % attr)
Exception: method "ERRORMETHOD" is not supported

**Comment by listyque** [comment]
Ok. It was caused by apparmor, or wrong ph_hba.
(i was using tactic rmp to install tactic this time)
