### ISSUE TITLE
Python3 related error in monitor.py

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1559]
**Describe the bug**
Traceback (most recent call last):
  File "/opt/tactic/tactic/src/bin/monitor.py", line 30, in <module>
    monitor.execute()
  File "/opt/tactic/tactic/src/pyasm/web/monitor.py", line 885, in execute
    self._execute()
  File "/opt/tactic/tactic/src/pyasm/web/monitor.py", line 1101, in _execute
    self.monitor()
  File "/opt/tactic/tactic/src/pyasm/web/monitor.py", line 1129, in monitor
    tactic_thread._check()
  File "/opt/tactic/tactic/src/pyasm/web/monitor.py", line 141, in _check
    start = time.clock()
AttributeError: module 'time' has no attribute 'clock'

I think is is related to python 3

**Comment by remkonoteboom** [comment]
Not sure why it is time.clock()  ... likely this used to work before.  I changed it to time.time() but commented it out because the variable that uses this variable (start) is commented out as well.
