### ISSUE TITLE
Checkin of a big file with the upload method fails

### ISSUE THREAD

**Issue by diegocortassa** [Southpaw-TACTIC/TACTIC#1600]
**Describe the bug**
Since commit 50c98843428290a075866d3414bb54ca5ddea665 checkin of a big file with the upload method fails (see "To Reproduce" for stack trace) there is a problem in src/pyasm/web/cherrypy30_startup.py line 401 `'server.socket_timeout': 0,` commenting the line solves the problem. I'm not sure why it was changed, is a PR welcome?

**To Reproduce**
1. Checkin a big file with "server.simple_checkin(search_key, process, file_path, mode="upload")
2. File upload fails with exception:
```
Traceback (most recent call last):
  File "H:\dcortassa\externals\tactic_client_lib\tactic_server_stub.py", line 2034, in simple_checkin
    self.upload_file(file_path)
  File "H:\dcortassa\externals\tactic_client_lib\tactic_server_stub.py", line 1880, in upload_file
    upload.execute(path)
  File "H:\dcortassa\externals\tactic_client_lib\common\upload_multipart.py", line 116, in execute
    (status, reason, content) = self.upload(self.server_url, fields, files)
TypeError: 'NoneType' object is not iterable
```
Server side:
```
[18/Feb/2021:17:16:28] ENGINE TypeError("object of type 'NoneType' has no len()")
Traceback (most recent call last):
File "/home/apache/tactic/3rd_party/python3/site-packages/cheroot/server.py", line 1273, in communicate
req.parse_request()
File "/home/apache/tactic/3rd_party/python3/site-packages/cheroot/server.py", line 720, in parse_request
success = self.read_request_line()
File "/home/apache/tactic/3rd_party/python3/site-packages/cheroot/server.py", line 761, in read_request_line
request_line = self.rfile.readline()
File "/home/apache/tactic/3rd_party/python3/site-packages/cheroot/server.py", line 303, in readline
data = self.rfile.readline(256)
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/_pyio.py", line 557, in readline
b = self.read(nreadahead())
File "/home/apache/tactic/3rd_party/python3/site-packages/cheroot/makefile.py", line 421, in read
self.bytes_read += len(val)
TypeError: object of type 'NoneType' has no len()
```

**Expected behavior**
Successful checkin returning a snapshot sobject

**Comment by remkonoteboom** [comment]
I had changed this line in order to make the REST interface work (otherwise it hangs), however, it seems to have consequences.  You can comment out and push.  I will have to find a workaround for the REST interface.

**Comment by diegocortassa** [comment]
Ok, I made PR  #1601, thanks.
